---
- name: Apache2
  hosts: an-loki
  become: true
  become_method: sudo
  become_user: adi
  become_flags: '-s /bin/sh'
  gather_facts: no
  tasks:
    - name: install apache2
      apt:
        name: apache2
        update_cache: yes
        state: latest
  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
